services:
  db:
    image: mariadb:10.6
    container_name: agendatech_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agendatech
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: agendatech_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

volumes:
  db_data: