import React,{useState,useEffect,useContext} from 'react';
import {AuthContext} from '../../../../contexts/AuthContext';
import {api,getFileUrl} from '../../../../services/api';
import {formatCurrency} from '../../../../utils/formatters';
import BadgeClassif from '../../../../components/shared/BadgeClassif';
import Button from '../../../../components/ui/Button';
import Input from '../../../../components/ui/Input';
import Select from '../../../../components/ui/Select';
import Textarea from '../../../../components/ui/Textarea';
import Modal from '../../../../components/ui/Modal';
import CalendarGrid from '../../../../components/shared/CalendarGrid';
import Spinner from '../../../../components/ui/Spinner';
import Toast from '../../../../components/ui/Toast';
import ChatBot from '../../../../components/shared/ChatBot';
import {FiSearch,FiMapPin,FiStar,FiClock,FiMessageCircle} from 'react-icons/fi';
export default function Explorar(){
  const {token}=useContext(AuthContext);
  const [dest,setDest]=useState([]);const [emps,setEmps]=useState([]);
  const [nichos,setNichos]=useState([]);const [cidades,setCidades]=useState([]);
  const [loading,setLoading]=useState(true);
  const [busca,setBusca]=useState('');const [nicho,setNicho]=useState('');const [cidade,setCidade]=useState('');
  const [sel,setSel]=useState(null);const [det,setDet]=useState(null);const [detL,setDetL]=useState(false);
  const [calData,setCalData]=useState({});const [calM,setCalM]=useState({y:new Date().getFullYear(),m:new Date().getMonth()+1});
  const [selServ,setSelServ]=useState(null);const [selDate,setSelDate]=useState(null);
  const [slots,setSlots]=useState([]);const [slotsL,setSlotsL]=useState(false);
  const [booking,setBooking]=useState(false);
  const [toast,setToast]=useState({visible:false,message:'',type:'success'});
  const [msgOpen,setMsgOpen]=useState(false);const [msgTxt,setMsgTxt]=useState('');
  var months=['Janeiro','Fevereiro','Marco','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
  useEffect(function(){Promise.all([api('GET','/api/empresas/destaques'),api('GET','/api/empresas/nichos'),api('GET','/api/empresas/cidades'),api('GET','/api/empresas?limite=20')]).then(function(r){if(r[0].success)setDest(r[0].data);if(r[1].success)setNichos(r[1].data);if(r[2].success)setCidades(r[2].data);if(r[3].success)setEmps(r[3].data);setLoading(false);});},[]);
  async function search(){setLoading(true);var url='/api/empresas?limite=20';if(busca)url+='&busca='+encodeURIComponent(busca);if(nicho)url+='&nicho='+encodeURIComponent(nicho);if(cidade)url+='&cidade='+encodeURIComponent(cidade);var r=await api('GET',url);if(r.success)setEmps(r.data);setLoading(false);}
  async function openDet(emp){setSel(emp);setDetL(true);setSelServ(null);setSelDate(null);setSlots([]);var r=await api('GET','/api/empresas/'+emp.id);if(r.success)setDet(r.data);setDetL(false);api('GET','/api/empresas/'+emp.id+'/calendario?ano='+calM.y+'&mes='+calM.m).then(function(cr){if(cr.success)setCalData(cr.data||{});});}
  async function loadSlots(date){if(!selServ||!sel)return;setSelDate(date);setSlotsL(true);var r=await api('GET','/api/empresas/'+sel.id+'/disponibilidade?servico_id='+selServ+'&data='+date);if(r.success)setSlots(r.data.slots||[]);else setSlots([]);setSlotsL(false);}
  async function book(slot){setBooking(true);var r=await api('POST','/api/agendamentos',{servico_id:parseInt(selServ),empresa_id:sel.id,data_agendamento:selDate,hora_inicio:slot.hora_inicio.substring(0,5)},token);setBooking(false);if(r.success){setToast({visible:true,message:'Agendado!',type:'success'});setSel(null);}else setToast({visible:true,message:r.message,type:'error'});}
  async function entrarFila(slot){var r=await api('POST','/api/fila',{servico_id:parseInt(selServ),empresa_id:sel.id,data_agendamento:selDate,hora_inicio:slot.hora_inicio.substring(0,5)},token);if(r.success)setToast({visible:true,message:'Entrou na fila!',type:'success'});else setToast({visible:true,message:r.message,type:'error'});}
  async function enviarMsg(){if(!msgTxt.trim()||!sel)return;var r=await api('POST','/api/mensagens/empresa/'+sel.id,{mensagem:msgTxt},token);if(r.success){setToast({visible:true,message:'Enviado!',type:'success'});setMsgTxt('');setMsgOpen(false);}else setToast({visible:true,message:r.message,type:'error'});}
  function chCal(d){var m=calM.m+d,y=calM.y;if(m<1){m=12;y--;}if(m>12){m=1;y++;}setCalM({y:y,m:m});if(sel)api('GET','/api/empresas/'+sel.id+'/calendario?ano='+y+'&mes='+m).then(function(cr){if(cr.success)setCalData(cr.data||{});});}
  if(loading)return <Spinner className="py-20"/>;
  function Card(e){return <button key={e.id} onClick={function(){openDet(e);}} className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-2xl overflow-hidden text-left hover:border-[var(--accent)] transition-colors group"><div className="h-24" style={{background:'linear-gradient(135deg,'+(e.cor_primaria||'#06b6d4')+','+(e.cor_secundaria||'#8b5cf6')+')'}}/><div className="p-4 -mt-6"><div className="w-10 h-10 rounded-xl bg-[var(--bg-secondary)] border-2 border-[var(--bg-surface)] overflow-hidden mb-2">{e.logo_url?<img src={getFileUrl(e.logo_url)} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center text-sm font-bold text-[var(--accent)]">{(e.nome_fantasia||'E')[0]}</div>}</div><h3 className="font-semibold text-[var(--text-primary)] group-hover:text-[var(--accent)] transition-colors">{e.nome_fantasia}</h3><BadgeClassif nicho={e.nicho} subNicho={e.sub_nicho}/><div className="flex items-center gap-3 mt-2 text-xs text-[var(--text-muted)]"><span className="flex items-center gap-1"><FiMapPin size={12}/>{e.cidade}</span>{e.media_avaliacao&&<span className="flex items-center gap-1"><FiStar size={12}/>{Number(e.media_avaliacao).toFixed(1)}</span>}</div></div></button>;}
  return(<div className="space-y-6">
    <Toast {...toast} onClose={function(){setToast(Object.assign({},toast,{visible:false}));}}/>
    <div><h1 className="text-2xl font-bold text-[var(--text-primary)]">Explorar</h1><p className="text-[var(--text-muted)]">Encontre empresas e agende</p></div>
    <div className="flex flex-wrap gap-3"><div className="flex-1 min-w-[200px]"><Input icon={FiSearch} placeholder="Buscar..." value={busca} onChange={function(e){setBusca(e.target.value);}} onKeyDown={function(e){if(e.key==='Enter')search();}}/></div><Select value={nicho} onChange={function(e){setNicho(e.target.value);}} options={[{value:'',label:'Nichos'}].concat(nichos.map(function(n){return{value:n.nicho,label:n.nicho+(n.sub_nicho?' / '+n.sub_nicho:'')};}))}/><Select value={cidade} onChange={function(e){setCidade(e.target.value);}} options={[{value:'',label:'Cidades'}].concat(cidades.map(function(c){return{value:c.cidade,label:c.cidade+' - '+c.estado};}))}/><Button onClick={search}>Buscar</Button></div>
    {dest.length>0&&<div><h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">Destaques</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{dest.map(Card)}</div></div>}
    <div><h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">Resultados</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{emps.map(Card)}{emps.length===0&&<p className="text-[var(--text-muted)] col-span-3 text-center py-8">Nenhuma</p>}</div></div>
    <Modal open={!!sel} onClose={function(){setSel(null);setDet(null);setSelServ(null);setSelDate(null);setSlots([]);}} title="Agendar" size="lg">
      {detL?<Spinner className="py-8"/>:det&&<div className="space-y-5">
        <div className="flex items-center gap-4"><div className="w-14 h-14 rounded-xl overflow-hidden bg-[var(--bg-surface)]">{det.logo_url?<img src={getFileUrl(det.logo_url)} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center text-xl font-bold text-[var(--accent)]">{(det.nome_fantasia||'E')[0]}</div>}</div><div className="flex-1"><h3 className="text-lg font-bold text-[var(--text-primary)]">{det.nome_fantasia}</h3><p className="text-sm text-[var(--text-muted)]">{det.descricao}</p></div><Button size="sm" variant="secondary" onClick={function(){setMsgOpen(true);}}><FiMessageCircle className="mr-1"/></Button></div>
        <div><label className="block text-sm font-medium text-[var(--text-secondary)] mb-2">Servico</label><div className="space-y-2">{(det.servicos||[]).map(function(s){return <button key={s.id} onClick={function(){setSelServ(s.id);setSelDate(null);setSlots([]);}} className={'w-full text-left p-3 rounded-xl border transition-colors '+(selServ===s.id?'border-[var(--accent)] bg-[var(--accent-muted)]':'border-[var(--border)] hover:border-[var(--accent)]')}><div className="flex items-center justify-between"><div><p className="font-medium text-[var(--text-primary)]">{s.nome}</p><p className="text-xs text-[var(--text-muted)] flex items-center gap-1"><FiClock size={12}/>{s.duracao_minutos}min</p></div><span className="text-[var(--accent)] font-bold">{formatCurrency(s.preco_base)}</span></div></button>})}</div></div>
        {selServ&&<div><div className="flex items-center justify-between mb-2"><button onClick={function(){chCal(-1);}} className="px-2 py-1 rounded hover:bg-[var(--bg-surface)] text-[var(--text-muted)]">←</button><span className="text-sm font-medium text-[var(--text-primary)]">{months[calM.m-1]} {calM.y}</span><button onClick={function(){chCal(1);}} className="px-2 py-1 rounded hover:bg-[var(--bg-surface)] text-[var(--text-muted)]">→</button></div><CalendarGrid year={calM.y} month={calM.m} data={calData} onDayClick={loadSlots} selectedDate={selDate}/></div>}
        {selDate&&<div><p className="text-sm font-medium text-[var(--text-secondary)] mb-2">Horarios {selDate}</p>{slotsL?<Spinner size="sm" className="py-4"/>:<div className="grid grid-cols-3 sm:grid-cols-4 gap-2">{slots.map(function(s,i){if(s.disponivel)return <button key={i} onClick={function(){book(s);}} disabled={booking} className="px-3 py-2 rounded-xl border border-[var(--border)] text-sm text-[var(--text-primary)] hover:border-[var(--accent)] hover:bg-[var(--accent-muted)] transition-colors disabled:opacity-50">{s.hora_inicio.substring(0,5)}</button>;return <button key={i} onClick={function(){entrarFila(s);}} className="px-3 py-2 rounded-xl border border-dashed border-[var(--text-muted)] text-sm text-[var(--text-muted)] hover:border-[var(--warning)] hover:text-[var(--warning)] transition-colors" title="Fila">{s.hora_inicio.substring(0,5)}<span className="block text-[10px]">fila</span></button>})}{slots.length===0&&<p className="col-span-4 text-sm text-[var(--text-muted)] text-center py-4">Sem horarios</p>}</div>}</div>}
        {det.avaliacoes&&det.avaliacoes.length>0&&<div><h4 className="text-sm font-medium text-[var(--text-secondary)] mb-2">Avaliacoes</h4><div className="space-y-2 max-h-40 overflow-y-auto">{det.avaliacoes.slice(0,5).map(function(av){return <div key={av.id} className="p-3 rounded-xl bg-[var(--bg-secondary)]"><div className="flex items-center gap-2 mb-1"><div className="flex">{[1,2,3,4,5].map(function(st){return <FiStar key={st} size={12} className={st<=av.estrelas?'text-amber-400 fill-amber-400':'text-[var(--border)]'}/>})}</div><span className="text-xs text-[var(--text-muted)]">{av.cliente_nome}</span></div>{av.feedback&&<p className="text-xs text-[var(--text-secondary)]">{av.feedback}</p>}</div>})}</div></div>}
      </div>}
    </Modal>
    <Modal open={msgOpen} onClose={function(){setMsgOpen(false);}} title="Enviar Mensagem"><div className="space-y-4"><Textarea value={msgTxt} onChange={function(e){setMsgTxt(e.target.value);}} rows={4} placeholder="Escreva sua mensagem..."/><div className="flex gap-3 justify-end"><Button variant="secondary" onClick={function(){setMsgOpen(false);}}>Cancelar</Button><Button onClick={enviarMsg}>Enviar</Button></div></div></Modal>
    <ChatBot empresaId={sel&&sel.id}/>
  </div>);
}