import React,{useState,useEffect,useContext} from 'react';
import {AuthContext} from '../../../../contexts/AuthContext';
import {api} from '../../../../services/api';
import Button from '../../../../components/ui/Button';
import Input from '../../../../components/ui/Input';
import Textarea from '../../../../components/ui/Textarea';
import Select from '../../../../components/ui/Select';
import Modal from '../../../../components/ui/Modal';
import Badge from '../../../../components/ui/Badge';
import Spinner from '../../../../components/ui/Spinner';
import Toast from '../../../../components/ui/Toast';
import {FiPlus,FiTrash2,FiEdit2} from 'react-icons/fi';
export default function Configuracoes(){
  const {token}=useContext(AuthContext);
  const [tab,setTab]=useState('regras');
  const [regras,setRegras]=useState([]);const [caps,setCaps]=useState([]);const [chatCfg,setChatCfg]=useState(null);
  const [faqs,setFaqs]=useState([]);const [tags,setTags]=useState([]);const [fila,setFila]=useState([]);
  const [loading,setLoading]=useState(true);const [modal,setModal]=useState(false);const [mtype,setMtype]=useState('');
  const [form,setForm]=useState({});const [toast,setToast]=useState({visible:false,message:'',type:'success'});
  async function loadAll(){setLoading(true);var r1=await api('GET','/api/regras-negocio',null,token);var r2=await api('GET','/api/empresa/capacidades',null,token);var r3=await api('GET','/api/mensagens/chat-config',null,token);var r4=await api('GET','/api/mensagens/chat-config/faq',null,token);var r5=await api('GET','/api/tags',null,token);var r6=await api('GET','/api/fila/empresa',null,token);if(r1.success)setRegras(r1.data);if(r2.success)setCaps(r2.data);if(r3.success)setChatCfg(r3.data);if(r4.success)setFaqs(r4.data);if(r5.success)setTags(r5.data);if(r6.success)setFila(r6.data);setLoading(false);}
  useEffect(function(){loadAll();},[token]);
  var tabs=[{key:'regras',label:'Regras'},{key:'capacidade',label:'Capacidade'},{key:'tags',label:'Tags'},{key:'fila',label:'Fila'},{key:'chat',label:'Chat/FAQ'}];
  function openM(t,d){setMtype(t);setForm(d||{});setModal(true);}
  function u(f){return function(e){setForm(function(p){var n=Object.assign({},p);n[f]=e.target.value;return n;});};}
  async function saveRegra(){var r=form.id?await api('PUT','/api/regras-negocio/'+form.id,form,token):await api('POST','/api/regras-negocio',form,token);if(r.success){setToast({visible:true,message:'Salvo!',type:'success'});setModal(false);loadAll();}else setToast({visible:true,message:r.message,type:'error'});}
  async function delRegra(id){if(!confirm('?'))return;await api('DELETE','/api/regras-negocio/'+id,null,token);loadAll();}
  async function saveCap(){var r=await api('POST','/api/empresa/capacidades',form,token);if(r.success){setModal(false);loadAll();}}
  async function delCap(id){await api('DELETE','/api/empresa/capacidades/'+id,null,token);loadAll();}
  async function saveChatCfg(){await api('PUT','/api/mensagens/chat-config',chatCfg,token);setToast({visible:true,message:'Salvo!',type:'success'});}
  async function saveFaq(){var r=form.id?await api('PUT','/api/mensagens/chat-config/faq/'+form.id,form,token):await api('POST','/api/mensagens/chat-config/faq',form,token);if(r.success){setModal(false);loadAll();}}
  async function delFaq(id){await api('DELETE','/api/mensagens/chat-config/faq/'+id,null,token);loadAll();}
  async function saveTag(){var b={nome:form.nome,label:form.label,cor:form.cor||'#888888',aceita_agendamento:form.aceita_agendamento!==undefined?form.aceita_agendamento:1,info:form.info};var r=form.id?await api('PUT','/api/tags/'+form.id,b,token):await api('POST','/api/tags',b,token);if(r.success){setToast({visible:true,message:'Tag salva!',type:'success'});setModal(false);loadAll();}else setToast({visible:true,message:r.message,type:'error'});}
  async function delTag(id){if(!confirm('?'))return;await api('DELETE','/api/tags/'+id,null,token);loadAll();}
  if(loading)return <Spinner className="py-20"/>;
  return(<div className="space-y-6"><Toast {...toast} onClose={function(){setToast(Object.assign({},toast,{visible:false}));}}/>
    <h1 className="text-2xl font-bold text-[var(--text-primary)]">Configuracoes</h1>
    <div className="flex gap-2 border-b border-[var(--border)] pb-2 overflow-x-auto">{tabs.map(function(t){return <button key={t.key} onClick={function(){setTab(t.key);}} className={'px-4 py-2 rounded-xl text-sm font-medium transition-colors whitespace-nowrap '+(tab===t.key?'bg-[var(--accent-muted)] text-[var(--accent)]':'text-[var(--text-muted)] hover:text-[var(--text-primary)]')}>{t.label}</button>})}</div>
    {tab==='regras'&&<div className="space-y-4"><Button onClick={function(){openM('regra',{tipo:'notificacao',nome:'',antecedencia_horas:24,mensagem_template:'',ativo:true});}}><FiPlus className="mr-2"/>Nova</Button>{regras.length===0&&<p className="text-[var(--text-muted)] text-center py-8">Nenhuma</p>}{regras.map(function(r){return <div key={r.id} className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-xl p-4 flex items-center justify-between"><div><div className="flex items-center gap-2"><h3 className="font-medium text-[var(--text-primary)]">{r.nome}</h3><Badge variant="info">{r.tipo}</Badge></div><p className="text-sm text-[var(--text-muted)] mt-1">{r.descricao}</p></div><div className="flex gap-1"><button onClick={function(){openM('regra',r);}} className="p-1.5 rounded-lg hover:bg-[var(--bg-surface-hover)]"><FiEdit2 size={16} className="text-[var(--text-muted)]"/></button><button onClick={function(){delRegra(r.id);}} className="p-1.5 rounded-lg hover:bg-red-500/10"><FiTrash2 size={16} className="text-[var(--text-muted)]"/></button></div></div>})}</div>}
    {tab==='capacidade'&&<div className="space-y-4"><Button onClick={function(){openM('cap',{hora_inicio:'',hora_fim:'',max_agendamentos:''});}}><FiPlus className="mr-2"/>Nova</Button>{caps.map(function(c){return <div key={c.id} className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-xl p-4 flex items-center justify-between"><p className="text-[var(--text-primary)]">{c.hora_inicio} - {c.hora_fim}: <strong>{c.max_agendamentos}</strong></p><button onClick={function(){delCap(c.id);}} className="p-1.5 rounded-lg hover:bg-red-500/10"><FiTrash2 size={16} className="text-[var(--text-muted)]"/></button></div>})}</div>}
    {tab==='tags'&&<div className="space-y-4"><Button onClick={function(){openM('tag',{nome:'',label:'',cor:'#888888',aceita_agendamento:1,info:''});}}><FiPlus className="mr-2"/>Nova Tag</Button><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{tags.map(function(t){return <div key={t.id} className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-xl p-4"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2"><span className="w-3 h-3 rounded-full" style={{background:t.cor||'#888'}}/><span className="font-medium text-[var(--text-primary)]">{t.label||t.nome}</span></div><div className="flex gap-1"><button onClick={function(){openM('tag',t);}} className="p-1 rounded hover:bg-[var(--bg-surface-hover)]"><FiEdit2 size={14} className="text-[var(--text-muted)]"/></button><button onClick={function(){delTag(t.id);}} className="p-1 rounded hover:bg-red-500/10"><FiTrash2 size={14} className="text-[var(--text-muted)]"/></button></div></div><p className="text-xs text-[var(--text-muted)]">{t.info}</p><Badge variant={t.aceita_agendamento?'success':'error'} className="mt-2">{t.aceita_agendamento?'Aceita':'Bloqueia'}</Badge></div>})}</div></div>}
    {tab==='fila'&&<div className="space-y-3">{fila.length===0&&<p className="text-[var(--text-muted)] text-center py-8">Fila vazia</p>}{fila.map(function(f){return <div key={f.id} className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-xl p-4 flex items-center justify-between"><div><p className="text-[var(--text-primary)] font-medium">{f.cliente_nome||'Cliente #'+f.cliente_id}</p></div><Badge variant={f.status==='aguardando'?'info':f.status==='notificado'?'warning':f.status==='convertido'?'success':'error'}>{f.status}</Badge></div>})}</div>}
    {tab==='chat'&&<div className="space-y-6"><div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-2xl p-5 space-y-4"><h3 className="font-semibold text-[var(--text-primary)]">Chat</h3><Textarea label="Mensagem abertura" value={chatCfg&&chatCfg.mensagem_abertura||''} onChange={function(e){setChatCfg(Object.assign({},chatCfg,{mensagem_abertura:e.target.value}));}} rows={3}/><label className="flex items-center gap-3 text-sm text-[var(--text-secondary)]"><input type="checkbox" checked={chatCfg&&chatCfg.ativo||false} onChange={function(e){setChatCfg(Object.assign({},chatCfg,{ativo:e.target.checked}));}} className="rounded"/>Ativo</label><Button onClick={saveChatCfg}>Salvar</Button></div><div><div className="flex items-center justify-between mb-4"><h3 className="font-semibold text-[var(--text-primary)]">FAQ</h3><Button size="sm" onClick={function(){openM('faq',{pergunta:'',resposta:'',ordem:faqs.length+1,ativo:true});}}><FiPlus className="mr-1"/>Nova</Button></div>{faqs.map(function(f){return <div key={f.id} className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-xl p-4 mb-2 flex items-center justify-between"><div><p className="font-medium text-[var(--text-primary)]">{f.pergunta}</p><p className="text-sm text-[var(--text-muted)]">{f.resposta}</p></div><div className="flex gap-1"><button onClick={function(){openM('faq',f);}} className="p-1.5 rounded-lg hover:bg-[var(--bg-surface-hover)]"><FiEdit2 size={16} className="text-[var(--text-muted)]"/></button><button onClick={function(){delFaq(f.id);}} className="p-1.5 rounded-lg hover:bg-red-500/10"><FiTrash2 size={16} className="text-[var(--text-muted)]"/></button></div></div>})}</div></div>}
    <Modal open={modal} onClose={function(){setModal(false);}} title={mtype==='regra'?'Regra':mtype==='cap'?'Capacidade':mtype==='tag'?'Tag':'FAQ'}><div className="space-y-4">
      {mtype==='regra'&&<><Select label="Tipo" value={form.tipo||'notificacao'} onChange={u('tipo')} options={[{value:'notificacao',label:'Notificacao'},{value:'cancelamento',label:'Cancelamento'},{value:'reagendamento',label:'Reagendamento'}]}/><Input label="Nome" value={form.nome||''} onChange={u('nome')}/><Textarea label="Descricao" value={form.descricao||''} onChange={u('descricao')} rows={2}/><Input label="Antecedencia (horas)" type="number" value={form.antecedencia_horas||''} onChange={u('antecedencia_horas')}/><Textarea label="Template" value={form.mensagem_template||''} onChange={u('mensagem_template')} rows={3} placeholder="{nome_cliente}, {servico}, {data}, {hora}"/><Button onClick={saveRegra} className="w-full">Salvar</Button></>}
      {mtype==='cap'&&<><Input label="Inicio" type="time" value={form.hora_inicio||''} onChange={u('hora_inicio')}/><Input label="Fim" type="time" value={form.hora_fim||''} onChange={u('hora_fim')}/><Input label="Max" type="number" value={form.max_agendamentos||''} onChange={u('max_agendamentos')}/><Button onClick={saveCap} className="w-full">Salvar</Button></>}
      {mtype==='tag'&&<><Input label="Nome" value={form.nome||''} onChange={u('nome')} placeholder="ex: feriado"/><Input label="Label" value={form.label||''} onChange={u('label')} placeholder="ex: Feriado"/><div><label className="block text-sm font-medium text-[var(--text-secondary)] mb-1.5">Cor</label><div className="flex items-center gap-3"><input type="color" value={form.cor||'#888888'} onChange={u('cor')} className="w-10 h-10 rounded-lg cursor-pointer"/><span className="text-sm text-[var(--text-muted)]">{form.cor||'#888888'}</span></div></div><Textarea label="Info" value={form.info||''} onChange={u('info')} rows={2}/><label className="flex items-center gap-3 text-sm text-[var(--text-secondary)]"><input type="checkbox" checked={form.aceita_agendamento!==0} onChange={function(e){setForm(function(p){var n=Object.assign({},p);n.aceita_agendamento=e.target.checked?1:0;return n;});}} className="rounded"/>Aceita agendamento</label><Button onClick={saveTag} className="w-full">Salvar</Button></>}
      {mtype==='faq'&&<><Input label="Pergunta" value={form.pergunta||''} onChange={u('pergunta')}/><Textarea label="Resposta" value={form.resposta||''} onChange={u('resposta')} rows={3}/><Input label="Ordem" type="number" value={form.ordem||''} onChange={u('ordem')}/><Button onClick={saveFaq} className="w-full">Salvar</Button></>}
    </div></Modal>
  </div>);
}