import React,{useState,useEffect,useContext} from 'react';
import {AuthContext} from '../../../../contexts/AuthContext';
import {api,getFileUrl} from '../../../../services/api';
import Badge from '../../../../components/ui/Badge';
import Button from '../../../../components/ui/Button';
import Textarea from '../../../../components/ui/Textarea';
import Spinner from '../../../../components/ui/Spinner';
import Toast from '../../../../components/ui/Toast';
import {FiStar} from 'react-icons/fi';
export default function PerfilEmpresaPublico(){
  const {token}=useContext(AuthContext);
  const [data,setData]=useState(null);const [loading,setLoading]=useState(true);
  const [stats,setStats]=useState(null);const [avs,setAvs]=useState([]);
  const [respId,setRespId]=useState(null);const [respTxt,setRespTxt]=useState('');
  const [toast,setToast]=useState({visible:false,message:'',type:'success'});
  async function load(){setLoading(true);var r1=await api('GET','/api/empresa/perfil',null,token);var r2=await api('GET','/api/avaliacoes/stats',null,token);var r3=await api('GET','/api/avaliacoes',null,token);if(r1.success)setData(r1.data);if(r2.success)setStats(r2.data);if(r3.success)setAvs(r3.data||[]);setLoading(false);}
  useEffect(function(){load();},[token]);
  async function responder(){if(!respTxt.trim())return;var r=await api('PUT','/api/avaliacoes/'+respId,{resposta:respTxt},token);if(r.success){setToast({visible:true,message:'Respondido!',type:'success'});setRespId(null);setRespTxt('');load();}else setToast({visible:true,message:r.message,type:'error'});}
  if(loading)return <Spinner className="py-20"/>;
  if(!data)return <p>Erro</p>;
  return(<div className="space-y-6 max-w-2xl"><Toast {...toast} onClose={function(){setToast(Object.assign({},toast,{visible:false}));}}/><h1 className="text-2xl font-bold text-[var(--text-primary)]">Perfil Publico</h1>
    <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-2xl overflow-hidden"><div className="h-32" style={{background:'linear-gradient(135deg,'+(data.cor_primaria||'#06b6d4')+','+(data.cor_secundaria||'#8b5cf6')+')'}}/><div className="p-6 -mt-10"><div className="w-16 h-16 rounded-2xl bg-[var(--bg-secondary)] border-4 border-[var(--bg-surface)] overflow-hidden mb-3">{data.logo_url?<img src={getFileUrl(data.logo_url)} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center text-xl font-bold text-[var(--accent)]">{(data.nome_fantasia||'E')[0]}</div>}</div><h2 className="text-xl font-bold text-[var(--text-primary)]">{data.nome_fantasia}</h2><p className="text-sm text-[var(--text-secondary)] mt-1">{data.descricao}</p><div className="flex gap-2 mt-3 flex-wrap">{data.nicho&&<Badge variant="info">{data.nicho}</Badge>}{data.sub_nicho&&<Badge>{data.sub_nicho}</Badge>}{data.cidade&&<Badge>{data.cidade} - {data.estado}</Badge>}</div></div></div>
    {stats&&<div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-2xl p-5"><h3 className="font-semibold text-[var(--text-primary)] mb-2">Avaliacoes</h3><div className="flex items-center gap-4"><div className="flex items-center gap-1"><FiStar className="text-amber-400 fill-amber-400" size={20}/><span className="text-2xl font-bold text-[var(--text-primary)]">{stats.media?Number(stats.media).toFixed(1):'-'}</span></div><span className="text-sm text-[var(--text-muted)]">{stats.total} avaliacoes</span></div><div className="mt-3 space-y-1">{[5,4,3,2,1].map(function(n){var keys=['um','dois','tres','quatro','cinco'];var count=stats[keys[n-1]]||0;var pct=stats.total>0?(count/stats.total*100):0;return <div key={n} className="flex items-center gap-2 text-sm"><span className="w-3 text-[var(--text-muted)]">{n}</span><FiStar size={12} className="text-amber-400 fill-amber-400"/><div className="flex-1 h-2 bg-[var(--bg-secondary)] rounded-full overflow-hidden"><div className="h-full bg-amber-400 rounded-full" style={{width:pct+'%'}}/></div><span className="text-[var(--text-muted)] w-8 text-right">{count}</span></div>})}</div></div>}
    <div className="space-y-3"><h3 className="text-lg font-semibold text-[var(--text-primary)]">Comentarios</h3>{avs.length===0&&<p className="text-[var(--text-muted)]">Nenhuma</p>}{avs.map(function(av){return <div key={av.id} className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-xl p-4 space-y-2"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="flex">{[1,2,3,4,5].map(function(s){return <FiStar key={s} size={14} className={s<=av.estrelas?'text-amber-400 fill-amber-400':'text-[var(--border)]'}/>})}</div><span className="text-xs text-[var(--text-muted)]">{av.cliente_nome||'Cliente'}</span></div>{!av.resposta_empresa&&<Button size="sm" variant="ghost" onClick={function(){setRespId(av.id);setRespTxt('');}}>Responder</Button>}</div>{av.feedback&&<p className="text-sm text-[var(--text-secondary)]">{av.feedback}</p>}{av.resposta_empresa&&<div className="ml-4 pl-3 border-l-2 border-[var(--accent)]"><p className="text-xs text-[var(--accent)] font-medium mb-1">Sua resposta</p><p className="text-sm text-[var(--text-secondary)]">{av.resposta_empresa}</p></div>}{respId===av.id&&<div className="mt-2 space-y-2"><Textarea value={respTxt} onChange={function(e){setRespTxt(e.target.value);}} rows={2} placeholder="Resposta..."/><div className="flex gap-2"><Button size="sm" onClick={responder}>Enviar</Button><Button size="sm" variant="ghost" onClick={function(){setRespId(null);}}>Cancelar</Button></div></div>}</div>})}</div>
  </div>);
}