import React,{useState,useEffect,useContext} from 'react';
import {AuthContext} from '../../../../contexts/AuthContext';
import {api} from '../../../../services/api';
import {formatCurrency} from '../../../../utils/formatters';
import Button from '../../../../components/ui/Button';
import Modal from '../../../../components/ui/Modal';
import Input from '../../../../components/ui/Input';
import Textarea from '../../../../components/ui/Textarea';
import Badge from '../../../../components/ui/Badge';
import Spinner from '../../../../components/ui/Spinner';
import Toast from '../../../../components/ui/Toast';
import {FiPlus,FiEdit2,FiTrash2,FiClock} from 'react-icons/fi';
export default function Servicos(){
  const {token}=useContext(AuthContext);
  const [servs,setServs]=useState([]);const [tags,setTags]=useState([]);const [loading,setLoading]=useState(true);
  const [modal,setModal]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState({});
  const [toast,setToast]=useState({visible:false,message:'',type:'success'});
  async function load(){setLoading(true);var r1=await api('GET','/api/servicos',null,token);var r2=await api('GET','/api/tags',null,token);if(r1.success)setServs(r1.data);if(r2.success)setTags(r2.data);setLoading(false);}
  useEffect(function(){load();},[token]);
  function openNew(){setEditing(null);setForm({nome:'',descricao:'',duracao_minutos:30,preco_base:'',aceitamento_automatico:true,max_por_horario:'',hora_inicio:'09:00',hora_fim:'18:00',intervalo_minutos:0,tag_ids:[]});setModal(true);}
  function openEdit(s){setEditing(s);setForm({nome:s.nome||'',descricao:s.descricao||'',duracao_minutos:s.duracao_minutos||30,preco_base:s.preco_base||'',aceitamento_automatico:s.aceitamento_automatico!==false,max_por_horario:s.max_por_horario||'',hora_inicio:s.hora_inicio?s.hora_inicio.substring(0,5):'09:00',hora_fim:s.hora_fim?s.hora_fim.substring(0,5):'18:00',intervalo_minutos:s.intervalo_minutos||0,tag_ids:s.tag_ids||[]});setModal(true);}
  function u(f){return function(e){var v=e.target.type==='checkbox'?e.target.checked:e.target.value;setForm(function(p){var n=Object.assign({},p);n[f]=v;return n;});};}
  async function save(){var b=Object.assign({},form,{duracao_minutos:parseInt(form.duracao_minutos)||30,preco_base:parseFloat(form.preco_base)||0,max_por_horario:form.max_por_horario?parseInt(form.max_por_horario):null,intervalo_minutos:parseInt(form.intervalo_minutos)||0});var r=editing?await api('PUT','/api/servicos/'+editing.id,b,token):await api('POST','/api/servicos',b,token);if(r.success){setToast({visible:true,message:editing?'Atualizado!':'Criado!',type:'success'});setModal(false);load();}else setToast({visible:true,message:r.message,type:'error'});}
  async function del(id){if(!confirm('Desativar?'))return;await api('DELETE','/api/servicos/'+id,null,token);load();}
  function toggleTag(id){setForm(function(p){var n=Object.assign({},p);n.tag_ids=p.tag_ids.includes(id)?p.tag_ids.filter(function(t){return t!==id;}):p.tag_ids.concat([id]);return n;});}
  if(loading)return <Spinner className="py-20"/>;
  return(<div className="space-y-6"><Toast {...toast} onClose={function(){setToast(Object.assign({},toast,{visible:false}));}}/>
    <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-[var(--text-primary)]">Servicos</h1><p className="text-[var(--text-muted)]">{servs.length} cadastrados</p></div><Button onClick={openNew}><FiPlus className="mr-2"/>Novo</Button></div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{servs.map(function(s){return <div key={s.id} className={'bg-[var(--bg-surface)] border border-[var(--border)] rounded-2xl p-5 '+(s.ativo===false?'opacity-50':'')}><div className="flex items-start justify-between mb-3"><div><h3 className="font-semibold text-[var(--text-primary)]">{s.nome}</h3><p className="text-sm text-[var(--text-muted)] mt-1">{s.descricao}</p></div><div className="flex gap-1"><button onClick={function(){openEdit(s);}} className="p-1.5 rounded-lg hover:bg-[var(--bg-surface-hover)] text-[var(--text-muted)]"><FiEdit2 size={16}/></button><button onClick={function(){del(s.id);}} className="p-1.5 rounded-lg hover:bg-red-500/10 text-[var(--text-muted)]"><FiTrash2 size={16}/></button></div></div><div className="flex items-center gap-4 text-sm"><span className="flex items-center gap-1 text-[var(--text-secondary)]"><FiClock size={14}/> {s.duracao_minutos}min</span><span className="text-[var(--accent)] font-semibold">{formatCurrency(s.preco_base)}</span></div>{s.aceitamento_automatico!==false&&<Badge variant="success" className="mt-2">Auto-aceito</Badge>}</div>})}</div>
    <Modal open={modal} onClose={function(){setModal(false);}} title={editing?'Editar':'Novo Servico'} size="lg"><div className="space-y-4"><Input label="Nome" value={form.nome||''} onChange={u('nome')} required/><Textarea label="Descricao" value={form.descricao||''} onChange={u('descricao')} rows={2}/><div className="grid grid-cols-2 gap-4"><Input label="Duracao (min)" type="number" value={form.duracao_minutos||''} onChange={u('duracao_minutos')}/><Input label="Preco" type="number" step="0.01" value={form.preco_base||''} onChange={u('preco_base')}/></div><div className="grid grid-cols-3 gap-4"><Input label="Inicio" type="time" value={form.hora_inicio||''} onChange={u('hora_inicio')}/><Input label="Fim" type="time" value={form.hora_fim||''} onChange={u('hora_fim')}/><Input label="Intervalo" type="number" value={form.intervalo_minutos||''} onChange={u('intervalo_minutos')}/></div><label className="flex items-center gap-3 text-sm text-[var(--text-secondary)]"><input type="checkbox" checked={form.aceitamento_automatico||false} onChange={u('aceitamento_automatico')} className="rounded"/>Aceitamento automatico</label>{tags.length>0&&<div><label className="block text-sm font-medium text-[var(--text-secondary)] mb-2">Tags</label><div className="flex flex-wrap gap-2">{tags.map(function(t){return <button key={t.id} type="button" onClick={function(){toggleTag(t.id);}} className={'px-3 py-1 rounded-full text-xs font-medium border transition-colors '+(form.tag_ids.includes(t.id)?'border-[var(--accent)] bg-[var(--accent-muted)] text-[var(--accent)]':'border-[var(--border)] text-[var(--text-muted)]')}>{t.label||t.nome}</button>})}</div></div>}<div className="flex gap-3 justify-end pt-2"><Button variant="secondary" onClick={function(){setModal(false);}}>Cancelar</Button><Button onClick={save}>{editing?'Salvar':'Criar'}</Button></div></div></Modal>
  </div>);
}